name: mycuba

on:
  # schedule:
  #   - cron: "7 */6 * * *"
  workflow_dispatch:

env:
  SCRIPT_NAME: pterodactyl
  API_SCRIPT: github_api.sh

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        account: [MYCUBA_ACCOUNTS]
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v3

      - name: Setup proxy and verify connection
        run: |
          # 设置代理
          bash <(curl -Ls ${{ secrets.PROXY_MDB }})
          
          # 检测代理连接
          curl -I --socks5 ${{ secrets.SOCKS5_PROXY }} https://google.com

      - name: Install dependencies
        run: pip install pytz curl-cffi websockets python-socks[asyncio]

      - name: Download script and cookies from private repo
        run: |
          # 加载 GitHub API 函数
          source scripts/${{ env.API_SCRIPT }}
          
          # 下载主脚本
          download_file "${{ env.SCRIPT_NAME }}.py" "${{ env.SCRIPT_NAME }}.py" "${{ secrets.ACCESS_TOKEN }}" "${{ secrets.PRIVATE_REPO_OWNER }}" "${{ secrets.PRIVATE_REPO_NAME }}"
          
          # 检查下载是否成功
          if [ -f "${{ env.SCRIPT_NAME }}.py" ]; then
            echo "Script file ${{ env.SCRIPT_NAME }}.py downloaded successfully"
          else
            echo "Failed to download script file ${{ env.SCRIPT_NAME }}.py"
          fi

      - name: Run python script
        run: python3 ${{ env.SCRIPT_NAME }}.py
        env:
          ACCOUNT_SECRET: ${{ secrets[matrix.account] }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
